document.write('<header>');
document.write('        <div class="header-top"></div>');
document.write('        <div>');
document.write('            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">');
document.write('                <i class="fa fa-bars" aria-hidden="true"></i>');
document.write('            </button>');
document.write('            <div class="collapse navbar-collapse">');
document.write('                <div class="nav-sec">');
document.write('                    <div class="container">');
document.write('                        <ul class="nav">');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link active" href="index.html">Home</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="about.html">About Me </a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="myblog.html">我的博客</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="editblog.html">写博客</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="comein.html?type=registe">注册</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="comein.html?type=login">登录</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <a class="nav-link" href="contact.html">意见与建议</a>');
document.write('                            </li>');
document.write('                            <li class="nav-item">');
document.write('                                <div class="search-sec">');
document.write('				                    <div class="search">');
document.write('				                        <input class="search-box" type="text" placeholder="Search here">');
document.write('				                        <span><i class="fa fa-search search-button" onclick=""></i></span>');
document.write('				                    </div>');
document.write('				                </div>');
document.write('                            </li>');
document.write('                        </ul>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('    </header>');
